export const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS farms (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      location TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      email TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'owner',
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS users_email_idx ON users(email)`,
  `CREATE TABLE IF NOT EXISTS sessions (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id),
      expires_at TEXT NOT NULL,
      created_at TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS cows (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      client_id TEXT NOT NULL,
      tag_number TEXT NOT NULL,
      name TEXT,
      breed TEXT,
      gender TEXT NOT NULL,
      birth_date TEXT,
      mother_tag TEXT,
      status TEXT NOT NULL DEFAULT 'active',
      notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      deleted_at TEXT
    )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS cows_client_id_idx ON cows(client_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS cows_farm_tag_idx ON cows(farm_id, tag_number) WHERE deleted_at IS NULL`,
  `CREATE TABLE IF NOT EXISTS milking_records (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      client_id TEXT NOT NULL,
      cow_id TEXT NOT NULL REFERENCES cows(id),
      date TEXT NOT NULL,
      session TEXT NOT NULL,
      liters DOUBLE PRECISION NOT NULL,
      notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      deleted_at TEXT
    )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS milk_client_id_idx ON milking_records(client_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS milk_cow_date_session_idx ON milking_records(cow_id, date, session) WHERE deleted_at IS NULL`,
  `CREATE TABLE IF NOT EXISTS health_events (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      cow_id TEXT NOT NULL REFERENCES cows(id),
      date TEXT NOT NULL,
      kind TEXT NOT NULL,
      status TEXT NOT NULL,
      diagnosis TEXT,
      treatment TEXT,
      medicine_name TEXT,
      isolated INTEGER NOT NULL DEFAULT 0,
      milk_withhold_until TEXT,
      notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
  `ALTER TABLE health_events ADD COLUMN IF NOT EXISTS milk_withhold_until TEXT`,
  `ALTER TABLE health_events ADD COLUMN IF NOT EXISTS photo_url TEXT`,
  `ALTER TABLE health_events ADD COLUMN IF NOT EXISTS photo_urls TEXT`,
  `ALTER TABLE farms ADD COLUMN IF NOT EXISTS digest_phone TEXT`,
  `ALTER TABLE farms ADD COLUMN IF NOT EXISTS digest_channel TEXT`,
  `CREATE TABLE IF NOT EXISTS kraals (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      name TEXT NOT NULL,
      notes TEXT,
      created_at TEXT NOT NULL
    )`,
  `ALTER TABLE cows ADD COLUMN IF NOT EXISTS kraal_id TEXT`,
  `ALTER TABLE cows ADD COLUMN IF NOT EXISTS photo_url TEXT`,
  `ALTER TABLE cows ADD COLUMN IF NOT EXISTS photo_urls TEXT`,
  `CREATE TABLE IF NOT EXISTS breeding_events (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      cow_id TEXT NOT NULL REFERENCES cows(id),
      date TEXT NOT NULL,
      kind TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'recorded',
      sire_tag TEXT,
      expected_calving TEXT,
      dry_off_date TEXT,
      notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS expenses (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      date TEXT NOT NULL,
      category TEXT NOT NULL,
      amount DOUBLE PRECISION NOT NULL,
      vendor TEXT,
      notes TEXT,
      recorded_by TEXT,
      created_at TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS milk_sales (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      date TEXT NOT NULL,
      liters DOUBLE PRECISION NOT NULL,
      price_per_liter DOUBLE PRECISION NOT NULL,
      total_amount DOUBLE PRECISION NOT NULL,
      buyer TEXT,
      notes TEXT,
      recorded_by TEXT,
      created_at TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS activity_log (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      user_id TEXT,
      user_name TEXT,
      action TEXT NOT NULL,
      entity TEXT NOT NULL,
      entity_id TEXT,
      detail TEXT,
      created_at TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS stock_items (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      unit TEXT NOT NULL,
      quantity DOUBLE PRECISION NOT NULL,
      reorder_level DOUBLE PRECISION NOT NULL DEFAULT 0,
      batch_code TEXT,
      expires_on TEXT,
      notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
  `ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS batch_code TEXT`,
  `ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS expires_on TEXT`,
  `CREATE TABLE IF NOT EXISTS stock_movements (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      item_id TEXT NOT NULL REFERENCES stock_items(id),
      kind TEXT NOT NULL,
      quantity DOUBLE PRECISION NOT NULL,
      reason TEXT,
      date TEXT NOT NULL,
      created_at TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS wash_records (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      date TEXT NOT NULL,
      method TEXT NOT NULL,
      chemical_name TEXT NOT NULL,
      mix_ratio TEXT,
      next_due TEXT,
      animal_scope TEXT NOT NULL,
      notes TEXT,
      created_at TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS farm_tasks (
      id TEXT PRIMARY KEY,
      farm_id TEXT NOT NULL REFERENCES farms(id),
      title TEXT NOT NULL,
      category TEXT NOT NULL,
      due_date TEXT NOT NULL,
      due_time TEXT,
      cow_id TEXT,
      status TEXT NOT NULL DEFAULT 'open',
      notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
];
