export const domainModules = [
  { name: "farm", phase: 1, path: "src/modules/farm" },
  { name: "users", phase: 1, path: "src/modules/users" },
  { name: "cattle", phase: 1, path: "src/modules/cattle" },
  { name: "milk", phase: 1, path: "src/modules/milk" },
  { name: "sync", phase: 1, path: "src/modules/sync" },
  { name: "health", phase: 1, path: "src/modules/health" },
  { name: "inventory", phase: 1, path: "src/modules/inventory" },
  { name: "wash", phase: 1, path: "src/modules/wash" },
  { name: "tasks", phase: 1, path: "src/modules/tasks" },
  { name: "alerts", phase: 1, path: "src/modules/alerts" },
  { name: "breeding", phase: 1, path: "src/modules/breeding" },
  { name: "finance", phase: 1, path: "src/modules/finance" },
  { name: "activity", phase: 1, path: "src/modules/activity" },
  { name: "kraals", phase: 1, path: "src/modules/kraals" },
  { name: "reports", phase: 1, path: "src/modules/reports" },
] as const;
